export { default as cot_co } from "./Co_Thoi_Loi.png";
export { default as hai_dang } from "./Hai Dang.png";
export { default as dinh_lang } from "./Dinh Lang.png";
export { default as trung_bay } from "./Nha Hang Trung Bay.png";
export { default as nui_lua } from "./Nui Lua.png";
export { default as chua } from "./Chua.png";
export { default as cang } from "./Cang bien.png";
export { default as star } from "./Star.png";
export { default as btn_thoat } from "./Nut Thoat.png";

export { default as cangSK } from "./CẢNG SA KÌ.jpg";
export { default as cangSK2 } from "./CANG SA KY.2.png";
export { default as chuaDuc } from "./CHUA DUC.1.png";
export { default as chuaDuc2 } from "./CHUA DUC.2.png";
export { default as chuaHang } from "./CHUA HANG.1.png";
export { default as chuaHang2 } from "./CHUA HANG.2.png";
export { default as cotCo1 } from "./COT CO TO QUOC.1.png";
export { default as cotCo2 } from "./COT CO TO QUOC.2.png";
export { default as anHai1 } from "./DINH LANG AN HAI.1.png";
export { default as anHai2 } from "./DINH LANG AN HAI.2.png";
export { default as anVinh1 } from "./DINH LANG AN VINH.1.jpg";
export { default as anVinh2 } from "./DINH LANG AN VINH.2.jpg";
export { default as haiDang1 } from "./NGON HAI DANG.1.jpg";
export { default as haiDang2 } from "./NGON HAI DANG.2.jpg";
export { default as trungBay1 } from "./NHA TRUNG BAY HAI DOI HOANG SA KIEM QUAN BAC HAI.png";
export { default as trungBay2 } from "./NHA TRUNG BAY HAI DOI HOANG SA KIEM QUAN BAC HAI.2.png";
export { default as giengTien1 } from "./NUI GIENG TIEN.1.png";
export { default as giengTien2 } from "./NUI GIENG TIEN.2.png";
export { default as thoiLoi1 } from "./NUI THOI LOI.1.png";
export { default as thoiLoi2 } from "./NUI THOI LOI.2.png";