export { default as question } from "./chamhoi.png";
export { default as diaDiem } from "./nut_danh_dau.png";
export { default as btn_thoat } from "./Nut Thoat.png";
export { default as daoAnBang } from "./daoanbang.jpg";
export { default as daoAnBang2 } from "./daoanbang.2.png";
export { default as daoSTT2 } from "./song-tu-tay-1.jpg";
export { default as daoSTT } from "./songtutay.2.jpg";
export { default as daoTSL } from "./daotruongsalon.jpg";
export { default as daoTSL2 } from "./Truong-Sa-Lon-.jpg";
export { default as muiTen } from "./Mui Ten.png";